### ISSUE TITLE
How do I save segmented point cloud?

### ISSUE THREAD

**Issue by ghost** [fverdoja/Fast-3D-Pointcloud-Segmentation#1]
Thanks for making your work available.

Is there any way to save the segmented/colored point cloud?

**Comment by fverdoja** [comment]
Hi,
There is no built in save function in my code because saving pointclouds is very well supported by the PCL library my code is based on.
Depending on what you need, you can extract the clusters with either `Clustering::get_colored_cloud()`
or `Clustering::get_labeled_cloud()`.
Then, you can save it following the instructions available [in this tutorial](http://www.pointclouds.org/documentation/tutorials/writing_pcd.php).

Hope this helps.
